CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  email TEXT NOT NULL,
  age INTEGER NOT NULL,
  is_artist INTEGER NOT NULL DEFAULT 0 CHECK (is_artist IN (0, 1))
);

CREATE TABLE IF NOT EXISTS songs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  author TEXT NOT NULL,
  duration_sec INTEGER NOT NULL DEFAULT 180,
  rating INTEGER NOT NULL DEFAULT 0,
  listen_count INTEGER NOT NULL DEFAULT 0,
  genres_text TEXT NOT NULL DEFAULT '',
  UNIQUE (name, author)
);