CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  email TEXT NOT NULL,
  age INTEGER NOT NULL,
  is_artist INTEGER NOT NULL DEFAULT 0 CHECK (is_artist IN (0, 1))
);
